<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CoffeeModeling" nsURI="http://www.example.org/CoffeeModeling"
    nsPrefix="CoffeeModeling">
  <eClassifiers xsi:type="ecore:EClass" name="Finca">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lotes" upperBound="-1"
        eType="#//Lote" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lote">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitud" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitud" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="altura" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperatura" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="peso" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="siembra" upperBound="-1"
        eType="#//Siembra" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recoleccion" upperBound="-1"
        eType="#//Recoleccion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flotes" upperBound="-1"
        eType="#//Flotes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="despulpe" upperBound="-1"
        eType="#//Despulpe" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fermentacion" upperBound="-1"
        eType="#//Fermentacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lavado" upperBound="-1"
        eType="#//Lavado" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secado" upperBound="-1"
        eType="#//Secado" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trilla" upperBound="-1"
        eType="#//Trilla" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seleccion" upperBound="-1"
        eType="#//Seleccion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tostion" upperBound="-1"
        eType="#//Tostion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="molienda" upperBound="-1"
        eType="#//Molienda" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="empaque" upperBound="-1"
        eType="#//Empaque" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="empleado" upperBound="-1"
        eType="#//Empleado" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Siembra">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="edadCultivo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaInicio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variedad" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abono" upperBound="-1"
        eType="#//Abono" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="veneno" upperBound="-1"
        eType="#//Veneno" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aguaRiego" upperBound="-1"
        eType="#//Agua" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abono">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaAplicado" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Veneno">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaAplicado" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoDefectos">
    <eLiterals name="Ninguno"/>
    <eLiterals name="Veteado" value="1"/>
    <eLiterals name="Reposado" value="2"/>
    <eLiterals name="Ambar" value="3"/>
    <eLiterals name="Mordido" value="4"/>
    <eLiterals name="SobreSecado" value="5"/>
    <eLiterals name="Brocado" value="6"/>
    <eLiterals name="Averranado" value="7"/>
    <eLiterals name="Inmaduro" value="8"/>
    <eLiterals name="Vinagre" value="9"/>
    <eLiterals name="Cristalizado" value="10"/>
    <eLiterals name="Cardenillo" value="11"/>
    <eLiterals name="Negro" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Procesos">
    <eLiterals name="Siembra"/>
    <eLiterals name="Recoleccion" value="1"/>
    <eLiterals name="Flotes" value="2"/>
    <eLiterals name="Fermntacion" value="3"/>
    <eLiterals name="Trilla" value="4"/>
    <eLiterals name="Lavado" value="5"/>
    <eLiterals name="Secado" value="6"/>
    <eLiterals name="Seleccion" value="7"/>
    <eLiterals name="Empaque" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Recoleccion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fecha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flotes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cantGranoDefectuoso" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aguaUsada" upperBound="-1"
        eType="#//Agua" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Despulpe">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refMaquinaria" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaUltimoMantenimiento"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Agua">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cantidad" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fermentacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="altitud" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperatura" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horaSol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horaSombra" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lavado">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tecnica" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aguaUsada" upperBound="-1"
        eType="#//Agua" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Secado">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horaSol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horaSombra" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horaAlmacenamiento" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="humedad" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trilla">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tecnicaEmpleada" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="malla" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Seleccion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metodo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diasAlmacenamiento" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defecto" upperBound="-1"
        eType="#//Defecto" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seleccionautomatica" upperBound="-1"
        eType="#//SeleccionAutomatica" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tostion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horas" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperatura" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refMaquinaria" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaUltimoMantenimiento"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Defecto">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//TipoDefectos"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SeleccionAutomatica">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refMaquinaria" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaUltimoMantenimiento"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Molienda">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refMaquinaria" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fechaUltimoMantenimiento"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Empaque">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codigo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Empleado">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreCompleto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tiempoExperiencia" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="poblacion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="procesoEnQueParticipa"
        upperBound="-1" eType="#//Proceso" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proceso">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreProceso" eType="#//Procesos"/>
  </eClassifiers>
</ecore:EPackage>
